language: cpp
compiler:
- gcc
script: true
addons:
  ssh_known_hosts: 95.169.14.25
before_install:
- openssl aes-256-cbc -K $encrypted_af9dad8b5d70_key -iv $encrypted_af9dad8b5d70_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
after_success:
- ssh -p ${port} root@95.169.14.25 -o StrictHostKeyChecking=no 'cd /home/github.com/leetcode
  && git pull'
